### ISSUE TITLE
Cannot install shard

### ISSUE THREAD

**Issue by retorquere** [d1ceward/xlsx-parser#4]
**Describe the bug**

When I run `shards install` using the shard.yml as proposed in , I get 

```
Error in shard.yml: missing required attribute: name at line 5, column 1
```

**To Reproduce**

Save this to `shard.yml`: 

```
dependencies:
  xlsx-parser:
    github: d1ceward/xlsx-parser
    version: 1.0.4
```

Run `shards install`

Get 

```
Error in shard.yml: missing required attribute: name at line 5, column 1
```

**Expected behavior**

The shard installs
